markdown: redcarpet
permalink: pretty
baseurl: /portfolio-working
exclude: ['README.md']
permalink: pretty
_config.yml
_includes/
_layouts/
_posts/
  └ 
css/
  └ main.css
  └ grid.css
  └ typography.css
images/
  └ 
index.html
project1.html